export const SET_SORT_BY = 'SET_SORT_BY'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const LOAD_PIZZAS = 'LOAD_PIZZAS'
export const SET_LOADING = 'SET_LOADING'
export const ADD_PIZZAS = 'ADD_PIZZAS'
export const REMOVE_CART = 'REMOVE_CART'